name: CI Pipeline
on:
  push:
    branches:
      - master 
      - feature
      
env:
        DOCKER_IMAGE: nivedanchauhan/petapp:${{ github.sha }}
        MAVEN_OPTS: "-DskipTests=true"      

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit

  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: test
     secrets: inherit       

  imagePublish:
    uses: ./.github/workflows/imagepush.yml
    needs: sonar
    secrets: inherit  
    